boardapp/urls.py
# from django.contrib import admin  # 管理者用のページを作成するためのモジュール
from django.urls import include, path
from . import settings
from django.conf.urls.static import static
from django.conf import settings
from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('', include('comments.urls')),
    #path('admin/', admin.site.urls),   # 管理者用のページを作成するためのモジュール
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), # staticファイルを配信するための設定
    re_path(r'^files/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}), # mediaファイルを配信するための設定
]


# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns.append(path("", include(debug_toolbar.urls)))

comments/urls.py
from django.urls import path
from . import views


app_name = 'comments'
urlpatterns = [
    path('', views.comments_index, name='index'),
    path('<int:comment_id>/', views.comments_show, name='show'),
    path('create/', views.comments_create, name='create'),
    path('<int:comment_id>/update/', views.comments_update, name='update'),
    path('<int:comment_id>/delete/', views.comments_delete, name='delete'),
    path('<int:comment_id>/reply/', views.comments_reply, name='reply'),
]

comments/models.py
from django.db import models
import os
from boardapp.settings import MEDIA_ROOT

# Create your models here.
class Comment(models.Model):
    body = models.CharField(max_length=2000)    # 本文
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='replies')
    file = models.FileField(upload_to='files', blank=True, null=True)
    password = models.CharField(max_length=6, blank=True, null=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.file:
            file_path = self.file.path
            file_dir, file_name = os.path.split(file_path)
            new_file_name = f"{self.id}{os.path.splitext(file_name)[1]}"
            new_file_path = os.path.join(MEDIA_ROOT, new_file_name)
            os.makedirs(os.path.dirname(new_file_path), exist_ok=True)
            os.rename(file_path, new_file_path)
            self.file.name = os.path.relpath(new_file_path, MEDIA_ROOT)
            super().save(update_fields=['file'])

    class Meta:
        ordering = ['-updated_at'] # 降順ソート

comments/forms.py
from django import forms
from .models import Comment
from django.core.validators import RegexValidator
from django.forms.widgets import ClearableFileInput

class CommentForm(forms.ModelForm):
    password = forms.CharField(
    widget=forms.PasswordInput(attrs={
        # 'class': 'form-control',
    }),
    validators=[RegexValidator(r'^\d{1,6}$', '6桁以下の数字を入力してください。')],
    label='パスワード（任意）',
    required=False
)

    class Meta:
        model = Comment
        fields = ('body', 'file', 'password',)
        widgets = {
            'body': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': '質問の内容を入力してください。画像添付の場合も何か記入してください。',
                'rows': '10'
            }),
            'file': ClearableFileInput(attrs={
                'class': 'form-control-file',
            }),
            # 'password': forms.PasswordInput(attrs={
            #     'class': 'form-control',
            # }),
        }
        labels = {
            'body': '',
            'file': '',
            'password': 'パスワード',
        }

    def clean(self):
        data = super().clean()
        body = data.get('body')
        if body is None:
            msg = "本文が入力されていません"
            self.add_error('body', msg)
        elif len(body) > 1000:
            msg = "本文の最大文字数は1000文字です"
            self.add_error('body', msg)

comments/views.py
from django.urls import reverse
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.contrib import messages
from .forms import CommentForm
from .models import Comment
import os
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger




# ページネーション機能
def paginate_queryset(request, queryset, count):
    paginator = Paginator(queryset, count)
    page = request.GET.get('page')
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        # ページ数が整数でない場合、最初のページを返す
        page_obj = paginator.page(1)
    except EmptyPage:
        # ページが存在しない場合、最後のページを返す
        page_obj = paginator.page(paginator.num_pages)
    return page_obj


# コメント一覧表示機能
def comments_index(request):
    paginate = request.GET.get(key="paginate", default="4")
    comments_list = Comment.objects.filter(parent_comment__isnull=True).order_by('-created_at')  # 返信を除外して親コメントのみ取得
    # comments_list = Comment.objects.all().order_by('-created_at') # 作成日時の降順で取得
    page_obj = paginate_queryset(request, comments_list, paginate)
    context = {
        'comments': page_obj.object_list,
        'page_obj': page_obj,
        'paginate': paginate,
    }
    return render(request, 'comments/index.html', context)


# コメント詳細表示機能
def comments_show(request, comment_id):
    context = {}
    comment = get_object_or_404(Comment, pk=comment_id)
    context['comment'] = comment


    # 返信がついていない場合
    if comment.parent_comment is None:
        # 直前（自身の直後に更新されたコメント）を取得する
        prev_comment = Comment.objects.filter(updated_at__gt=comment.updated_at).exclude(parent_comment__isnull=False).order_by('updated_at').first()

        # 直後（自身の直前に更新されたコメント）を取得する
        next_comment = Comment.objects.filter(updated_at__lt=comment.updated_at).exclude(parent_comment__isnull=False).order_by('-updated_at').first()

        if prev_comment is not None:
            prev_id = prev_comment.id
        else:
            prev_id = False
        if next_comment is not None:
            next_id = next_comment.id
        else:
            next_id = False
        context['prev_id'] = prev_id
        context['next_id'] = next_id
    else:
        # 次のparent_commentがないコメントを取得する
        next_parent_comment = Comment.objects.filter(parent_comment=comment.parent_comment, updated_at__gt=comment.updated_at).exclude(parent_comment__isnull=False).order_by('updated_at').first()

        # 次のparent_commentが存在する場合はそのコメントを取得する
        if next_parent_comment is not None:
            next_comment = next_parent_comment
        else:
            # 直前（自身の直後に更新されたコメント）を取得する
            prev_comment = Comment.objects.filter(updated_at__gt=comment.updated_at).exclude(parent_comment__isnull=False).order_by('updated_at').first()

            # 直後（自身の直前に更新されたコメント）を取得する
            next_comment = Comment.objects.filter(updated_at__lt=comment.updated_at).exclude(parent_comment__isnull=False).order_by('-updated_at').first()

            if prev_comment is not None:
                prev_id = prev_comment.id
            else:
                prev_id = False
            if next_comment is not None:
                next_id = next_comment.id
            else:
                next_id = False
            context['prev_id'] = prev_id
            context['next_id'] = next_id
    
    return render(request, 'comments/show.html', context)


# コメント投稿機能
def comments_create(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment()
            # comment.title = form.cleaned_data.get('title')
            comment.body = form.cleaned_data.get('body')
            comment.file = form.cleaned_data.get('file')
            comment.password = form.cleaned_data.get('password')
            
            # ファイルをアップロードして保存
            file = request.FILES.get('file')
            if file:
                comment.file = file
            comment.save()
            messages.success(request, 'コメントを投稿しました。', extra_tags='success_message')
            return redirect(reverse('comments:index'))
        else:
            # エラーメッセージをつけて返す
            context = {}
            context['page_title'] = 'コメントの投稿'
            context['form_name'] = 'コメントの投稿'
            context['button_label'] = 'コメントを投稿する'
            context['form'] = form
            return render(request, 'comments/form.html', context)
    else:
        context = {}
        context['form'] = CommentForm(
            initial={
            }
        )
        context['page_title'] = 'コメントの投稿'
        context['form_name'] = 'コメントの投稿'
        context['button_label'] = 'コメントを投稿する'
        return render(request, 'comments/form.html', context)


# パスワード認証機能
def password_auth(view_func):
    def wrapped_view(request, *args, **kwargs):
        # パスワード認証処理
        comment_id = kwargs.get('comment_id')
        password = request.POST.get('password')

        #  コメントを取得
        comment = get_object_or_404(Comment, pk=comment_id)

        # パスワードの確認
        if password == comment.password:
            return view_func(request, *args, **kwargs)
        else:
            messages.error(request, 'パスワードが違います。', extra_tags='error_message')
            return redirect(reverse('comments:index'))
    return wrapped_view


# コメント編集機能
def comments_update(request, comment_id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid(): 
            comment = get_object_or_404(Comment, pk=comment_id)
            password = form.cleaned_data.get('password')

            # パスワード認証
            if password == comment.password:
                comment.body = form.cleaned_data.get('body')
                # ファイルをアップロードして保存
                file = request.FILES.get('file')
                if file:
                    comment.file = file

                comment.save()
                messages.success(request, 'コメントを更新しました。', extra_tags='success_message')
                return redirect(reverse('comments:index'))
            else:
                messages.error(request, 'パスワードが違います。', extra_tags='error_message')
                return redirect(reverse('comments:index'))
        else:
            context = {}
            context['page_title'] = 'コメントの編集'
            context['form_name'] = 'コメントの編集'
            context['button_label'] = 'コメントを更新する'
            context['form'] = form
            return render(request, 'comments/form.html', context)
    else:
        context = {}
        comment = get_object_or_404(Comment, pk=comment_id)
        context['form'] = CommentForm(
            initial={
                'body' : comment.body,
            }
        )
        context['comment'] = comment
        context['page_title'] = 'コメントの編集'
        context['form_name'] = 'コメントの編集'
        context['button_label'] = 'コメントを更新する'
        return render(request, 'comments/form.html', context)
    

# コメント削除機能
def comments_delete(request, comment_id):
    if request.method == 'POST':
        comment = get_object_or_404(Comment, pk=comment_id)
        password = request.POST.get('password')

        # パスワード認証
        if password == comment.password:
            # 関連するファイルを削除
            if comment.file:
                file_path = comment.file.path
                if os.path.exists(file_path):
                    os.remove(file_path)

            # 返信コメントも削除し、関連するファイルも削除
            child_comments = Comment.objects.filter(parent_comment=comment)
            for child_comment in child_comments:
                if child_comment.file:
                    file_path = child_comment.file.path
                    if os.path.exists(file_path):
                        os.remove(file_path)
                child_comment.delete()

            comment.delete()
            messages.success(request, 'コメントを削除しました。', extra_tags='success_message')
            return redirect(reverse('comments:index'))
        else:
            messages.error(request, 'パスワードが違います。', extra_tags='error_message')
            return redirect(reverse('comments:index'))
    else:
        context = {}
        comment = get_object_or_404(Comment, pk=comment_id)
        context['comment'] = comment
        context['page_title'] = 'コメントの削除'
        context['form_name'] = 'コメントを削除しますか'
        context['button_label'] = 'コメントを削除する'
        return render(request, 'comments/delete_confirm.html', context)


# 返信追加機能
def comments_reply(request, comment_id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            parent_comment = get_object_or_404(Comment, pk=comment_id)
            comment = form.save(commit=False)
            comment.parent_comment = parent_comment
            # ファイルをアップロードして保存
            file = request.FILES.get('file')
            if file:
                comment.file = file
            comment.save()
            messages.success(request, '返信を投稿しました。', extra_tags='success_message')
            return redirect(reverse('comments:index'))
        else:
            # エラーメッセージをつけて返す
            context = {}
            context['page_title'] = 'コメントの返信'
            context['form_name'] = 'コメントの返信'
            context['button_label'] = 'コメントに返信する'
            context['form'] = form
            return render(request, 'comments/form.html', context)
    else:
        context = {}
        context['form'] = CommentForm(
            initial={
            }
        )
        context['page_title'] = 'コメントの返信'
        context['form_name'] = 'コメントの返信'
        context['button_label'] = 'コメントに返信する'
        return render(request, 'comments/form.html', context)


   

comments/templates/comments/delete_confirm.html
{% extends "base.html" %}
 
{% block title %}
{{ page_title }}
{% endblock %}
 
{% block content %}
    <div class="container">
        <h1 class="my-5">{{ form_name }}</h1>
        <hr>
 
        <div class="card mb-3">
            <div class="card-body">
                <p class="card-text">{{ comment.body }}</p>
                {% if comment.file %}
                    <img class="card-text img-fluid" src="{{ comment.file.url }}"/>
                {% endif %}
            </div>
            <div class="card-footer">
                Created at : {{ comment.created_at }}<br>
                Updated at : {{ comment.updated_at }}
            </div>
        </div>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="password">パスワード:</label>
                <input type="password" name="password">
            </div>
            <button type="submit" value="password" class="btn btn-primary">{{ button_label }}</button>
        </form>




        <hr>
        <p>
            <a href="{% url 'comments:show' comment.id %}">
               [ 詳細ページに戻る ]
            </a>
        </p>
    </div>
{% endblock content %}

comments/templates/comments/form.html
{% extends 'base.html' %}
 
{% block title %}
{{ page_title }}
{% endblock %}
 
{% block content %}
    <div class="container">
        <h1 class="my-5">{{ form_name }}</h1>
        <form method="POST" enctype="multipart/form-data" autocomplete="off">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">{{ button_label }}</button>
        </form>
        

        {% if comment.id %}
            <hr>
            <p>
                <a href="{% url 'comments:show' comment.id %}">
                    [ 詳細ページに戻る ]
                </a>
            </p>
        {% else %}
            <hr>
            <p>
                <a href="{% url 'comments:index' %}">
                    [ 一覧ページに戻る ]
                </a>
            </p>
        {% endif %}
        
    </div>
{% endblock content %}

comments/templates/comments/index.html
{% extends 'base.html' %}

{% block title %}
入門プログラミングの質問箱
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="my-5">Q&Aリスト / Q&A List</h1>
    {% for comment in comments %}
        {% if comment.parent_comment is None %}
            <div class="card mb-3">
                <div class="card-body">
                    <div style="display: flex; align-items: center;">
                        <p class="card-text" style="flex-grow: 1;">
                            {% if comment.body|length > 100 %}
                                <span id="comment-truncated-{{ comment.id }}">
                                    {{ comment.body | slice:":100" }}
                                </span>
                                <span id="comment-toggle-{{ comment.id }}" class="comment-toggle">... <a href="#" data-comment-id="{{ comment.id }}">read more</a></span>
                                <span id="comment-full-{{ comment.id }}" class="comment-full" style="display: none;">{{ comment.body }}</span>
                            {% else %}
                                {{ comment.body }}
                            {% endif %}
                        </p>
                        <a href="{% url 'comments:show' comment.id %}" style="margin-left: 20px;"><i class="fa-solid fa-circle-chevron-right"></i></a>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
    {% include 'simple_pagination.html' %}
    <hr>
    <div>
        <p>
            <a href="{% url 'comments:create' %}">
                新規コメントの投稿
            </a>
        </p>
    </div>
</div>

<script>
    let commentToggles = document.getElementsByClassName("comment-toggle");
    for (let i = 0; i < commentToggles.length; i++) {
        commentToggles[i].addEventListener("click", function(event) {
            event.preventDefault(); // デフォルトの動作をキャンセル
            let commentId = this.querySelector("a").getAttribute("data-comment-id");
            let commentTruncated = document.getElementById("comment-truncated-" + commentId);
            let commentFull = document.getElementById("comment-full-" + commentId);
            commentTruncated.style.display = "none";
            commentFull.style.display = "inline";
            this.style.display = "none"; // "read more" リンクも非表示にする
        });
    }
</script>

{% endblock content %}

comments/templates/comments/show.html
{% extends 'base.html' %}

{% block title %}
コメント {{ comment.id }}
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="my-5"></h1>
    <div class="text-right">
        <button type="button" class="btn btn-success mb-3" onclick="location.href='{% url 'comments:reply' comment.id %}'">
            返信 
        </button>
    </div>
    <div class="card mb-3">
        <div class="card-body">
            <p class="card-text">{{ comment.body }}</p>
            {% if comment.file %}
                <img class="card-text img-fluid" src="{{ comment.file.url }}"/>
            {% endif %}
        </div>
        <div class="card-footer">
            Created at : {{ comment.created_at }}<br>
            Updated at : {{ comment.updated_at }}
        </div>
    </div>

    {% if comment.id %}
        {% for reply in comment.replies.all %}
                <div class="reply">
                    <div class="card mb-3">
                        <div class="card-body">
                            <p class="card-text">{{ reply.body }}</p>
                            {% if reply.file %}
                            <img class="card-text img-fluid" src="{{ reply.file.url }}"/>
                            {% endif %}
                        </div>
                        <div class="card-footer">
                            Created at : {{ reply.created_at }}
                        </div>
                    </div>
                </div>
                {% empty %}
                    <p>このコメントにはまだ返信がありません。</p>
        {% endfor %}
    {% endif %}
    <hr>

    <div>
        <p>
            <a href="{% url 'comments:update' comment.id %}">
               [ 編集 ]
            </a>
            <a href="{% url 'comments:delete' comment.id %}">
               [ 削除 ]
            </a>
        </p>

        <p>
            <a href="{% url 'comments:index' %}">
               [ 一覧に戻る ]
        </p>
    </div>
    {% include 'prev_next.html' %}
</div>
{% endblock content %}